/* eslint-disable  func-names */
/* eslint quote-props: ["error", "consistent"]*/
/**
 * This sample demonstrates a simple skill built with the Amazon Alexa Skills
 * nodejs skill development kit.
 * This sample supports multiple lauguages. (en-US, en-GB, de-DE).
 * The Intent Schema, Custom Slots and Sample Utterances for this skill, as well
 * as testing instructions are located at https://github.com/alexa/skill-sample-nodejs-fact
 **/

'use strict';
const Alexa = require('alexa-sdk');

//=========================================================================================================================================
//TODO: The items below this comment need your attention.
//=========================================================================================================================================

//Replace with your app ID (OPTIONAL).  You can find this value at the top of your skill's page on http://developer.amazon.com.
//Make sure to enclose your value in quotes, like this: const APP_ID = 'amzn1.ask.skill.bb4045e6-b3e8-4133-b650-72923c5980f1';
const APP_ID = undefined;

const SKILL_NAME = 'Badass Woman Facts';
const GET_FACT_MESSAGE = "Here's your fact: ";
const HELP_MESSAGE = 'You can say tell me a badass woman fact, or, you can say exit... What can I help you with?';
const HELP_REPROMPT = 'What can I help you with?';
const STOP_MESSAGE = 'Goodbye!';

//=========================================================================================================================================
//TODO: Replace this data with your own.  You can find translations of this data at http://github.com/alexa/skill-sample-node-js-fact/lambda/data
//=========================================================================================================================================
const data = [
    'A talented British mathematician born in 1815, Augusta Ada Lovelace, is considered the first computer programmer.',
    'American Mae Carol Jemison, born in 1956, was the first black woman to travel in space orbit aboard the Space Shuttle Endeavour.',
    'Amal Clooney is a Lebanese-British human rights lawyer. She argued for recognition of the Armenian Genocide, she speaks 3 languages, studied at Oxford and New York University School of law, and the actor George Clooney is married to her.',
    'Simone Biles, born in 1997, is the most decorated American gymnast, with 19 Olympic and World Championship medals. She is the first female African-American all-around world champion and is recognized as One of the Most Influential People in the World by Time magazine.',
    'Malala Yousafzai, born in 1997 in Pakistan, is the youngest recipient of the Nobel Peace Prize. She was shot in the head by a Taliban member in 2012, but she did not let that stop her from advocating for girl\'s education. July 12th is recognized by the United Nation\'s as World Malala Day',
    'Mikalya Holmgren, born in 1995, is the first American woman with Down syndrome to compete in the Miss Minnesota USA pageant. She\'s competed in gymnastics in the Special Olympics and in 2015 she won the Junior Miss Amazing competition.',
    'Tarana Burke is an American civil rights activist who coined the phrase Me Too to raise awareness of widespread sexual abuse and harassment. Tarana was named one of Time magazines Person of the Year recipients in 2017.',
    'American Physist Katharine Blodgett was the first woman to receive her Ph.D. from Cambridge University. She is best known for her invention of low-reflectance glass, which is used in camera lenses, eyeglasses, car windshields, and computer screens.',
    'Michelle Obama is an American lawyer, writer, and former First Lady. She was the first black American to become First Lady. As First Lady, she advocated for low income Americans, military families, LGBT rights, and reducing childhood obesity through the Let\'s Move Campaign. Her signature style made her an international fashion icon.',
    'Joan Ruth Bader Ginsburg is an American lawyer and the second female justice named to the Supreme Court. She co-founded the Women\'s Right\'s Project at the American Civil Liberties Union. The Notorious RBG even has a species of praying mantis named after her.',
    'Elizabeth Marie Tall Chief was America\'s first prima ballerina, and the first Native American woman to hold this title. She was a passionate and technically precise performer, and she challenged ethnic stereotypes in the ballet world.',
    'Maya Angelou was an American writer and civil rights activist. Her book titled I know why the caged bird sings received international recognition, drawing attention to sexual abuse and women\'s personal lives. She read one of her poems at President Bill Clinton\'s inauguration, making her the first female poet to hold this honor. ',
    'Wilma Mankiller was an American women\'s rights activist and the first contemporary woman to serve as the principal Chief of the Cherokee nation. She was awarded the Presidential Medal of Freedom for her work and she is a member of the National Women\'s Hall of Fame.',
    'Ava DuVernay is a prominent American filmmaker. In 2012, she became the first black American woman to win the U.S. Directing Award for her film the Middle of Nowhere. She has won numerous awards for her writing, directing, and producing, such as Best Woman Director of the Year and Female Icon of the Year for her film Selma from the Alliance of Women in Film Journalists, and two Primetime Emmy Awards, among others, she also has a barbie made in her likeness.',
    'Patsy Mink, born in 1927, was the first American woman of Asian descent elected to Congress. She was a principle author of the Title 9 Amendment to Higher Education, she introduced the Childhood Education and Women\'s Educational Equity Acts, and she served 6 terms in Congress.',
    'Linda Sarsour is an American civil rights activist. Linda was one of three women co-chairing the 2017 women\'s march, a worldwide protest centered on human rights. She advocates for the rights of Muslim Americans and supports the Black Lives Matter movement. She was named one of Time magazine\'s 100 most influential people. ',
    'American Nancy Lopez, born in 1957, is considered one of the best professional female golfers. She has over 50 professional wins and three major championship titles, and she is and a strong advocate for women\'s rights.',
    'Grace Hopper, born in 1906, was an American computer scientist and member of the US Naval Reserves. Grace developed one of the first compiler tools and spearheaded compiler-based programming languages. She was awarded the Presidential Medal of Honor, dozens of honorary university degrees, and is remembered for the metal wires she passed out as a visual aid during her talks. ',
    'American Ameila Earhart, born in 1897, was the first woman to fly alone across the Atlantic Ocean. She was an educator, an engineer, a writer and an advocate for women in aviation.',
    'Beyonce Knowles-Carter is an American performer with international fame. A singer, song writer, dancer, actress, feminist, and philantrhopist, and she is one of the best-selling music artists, and higest paid black performers, in history. She has 22 grammy awards, 24 MTV Music Awards, numerous record setting albums, and the wrapper Jay-Z is married to her. ',
    'Frida Kahlo was a famous Mexican artist. Impacted by polio as a child, and a traffic accident as a young adult, she did not let that stop her. Her paintings have earned her a place in art history and she remains an icon for feminist movements.',
    'Hillary Clinton is an American politician and is the first female candidate nominated for president by the Democratic Party. A former First Lady, Senator, and Secretary of State, she won the popular vote in 2016 and showed us all how to stand up to bullies with grace and intelligence.',
    'Trisha Shetty is the founder and CEO of SheSays, an NGO that aims to empower women in India to take action against sexual harassment. She is a feminist, social activist and lawyer. She is one of the United Nations Sustainable Development Goals Young Leaders.',
    'Rita Kimani is a Kenyan computer scientist and co-founder and CEO of Farm Drive. Farm Drive helps connect underserved farmers to affordable credit. Rita is one of the United Nation\'s Sustainable Development Goals Young Leaders.',
    'Edda Hamar, from Australia and Iceland, co-founded Undress Runways and launched the Naked Mag in 2014 to educate and inspire people about sustainable fashion without compromising on style. She is one of the United Nation\'s Sustainable Development Goals Young Leaders.',
    'Safaath Zahir from the Repbulic of Maldives is a women\'s rights activist who leads Women on Boards, an non-profit promoting gender diversity in the workplace. Safaath is working to get more women in government and policy positions and she is one of the United Nation\'s Sustainable Development Goals Young Leaders.',
    'Columbian Carolina Medina is a co-founder and CEO of Agruppa. Agruppa leverages mobile phone technology to organize small businesses into clusters creating a virtual buying group so that suppliers can provide more afforable prices to customers. She is one of the United Nation\'s Sustainable Development Goals Young Leaders.',
   'Shougat Nazbin Khan from Bangladesh founded her own school, H.A. Digital School and College, to reach underserved communities and empower women. The school has a majority female faculty and over 600 students. Shougat won the Green Talent award in 2015 for her low-cost solar PV irrigation system and she is one of the United Nation\'s Sustainable Development Gloals Young Leaders.',
   'Samar Mezghanni is a Tunisian writer who capitivates audiences with her storytelling. She is in the Guiness Book of world records for being the youngest and most prolific writer in the world, and she has been named one of the most powerful Arab women. Encouraging young people to write about the world that they want to see, Samir is one of United Nation\'s Sustainable Development Gloals Young Leaders.',
   'Canadian Nikki Fraser stands up for the rights of indigenous women, bringing to light the numerous lost women who are missing with unexplained circumstances. A mother of two, she is the Youth Representative from British Columbia Native Women\'s Association and National Youth Representative for the Native Women\’s Association of Canada. She was a young leader selected to interview Prime Minister Justin Trudeau and she is one of United Nation\'s Sustainable Development Gloals Young Leaders.',
   'Tere Garcia is the president of Liter of Light in Mexico, an organization that repurposes plastic soda bottles to create sustainable light sources. Working with organizations like the World Bank and MTV Agents of Change, she encourages young people to enact positive change in society. She is one of United Nation\'s Sustainable Development Gloals Young Leaders.',
   'American Sheryl Sandberg is a technology executive, author, and philanthropist. Currently the chief operating officer of Facebook, she is the founder of the organization Lean In. She has authored three books aimed at helping women advance in the workforce, she frequently appears in listings of most influential people, and she contributed more than a hundred million dollars in Facebook stock to fund charitable efforts through the Sheryl Sandberg and Dave Goldberg Family Foundation.',
   'Kimberly Bryant is an American technologist, engineer, and the founder of Black Girls Code. Knowing the isolation that women face in science and tech, especially minority women, Kimberly wanted a better environment for her daughter and others to learn in, so she made one. Kimberly has been recognized as a White House champion of Change for Tech inclusion and voted one of the 25 most influential African Americans in Technolgy by Business Insider.',
   'Erica Baker is an American engineer and technology executive, renowned for her support for diversity and inclusion in tech. Erica has worked for tech companies such as Google, Slack, Kickstarter and Patreon. At Google, she created an internal spreadsheet where employees could willingly disclose their salaries, sparking discussion on disparities in pay based on gender and ethnicity. She carries this passion for equitable pay forward through initiatives such as the hastag Real Diversity Numbers, a Twitter movement to encourage companies to report about diversity.',
   'Tracy Chou is an American software engineer with experience at companies such as Google, Facebook, Quora, and RocketFuel. She is recognized as an advocate for diversity in tech and she co-founded Project Include with 7 other women. She created a public Github repository where companies can report their diversity numbers and is credited as being influential in getting high profile tech companies like Microsoft to start reporting their diversity numbers.',
   'Gwynne Shotwell is an American engineer and excutive, currently the President and Chief Operating Officer at SpaceX, a space exploration company. When she\'s not helping deliver astronauts to the International Space Station, she participates in a variety of science, technology, math and engineering initiatives. In 2012, she was added to the Women in Technology Hall of Fame.',
   'Jane Goodall is a British primatologist and anthropologist best known for her study of chimpanzees and advocacy on animal welfare issues. She was made a Dame, she\'s a United Nation\'s Messenger for Peace, and she has received dozens of awards for her research and advocacy. She even has a plaque on the Tree of Life at Walt Disney World\'s Animal Kingdom theme park.',
   'American Ann Dunwoody achieved a lot of firsts for women in the United States military. She was the first woman to command a battalion in the 82nd Airborne Division, the first female General officer at Fort Bragg, the first woman to command the Combined Arms Support Command at Fort Lee, and the first woman in the United States military to achieve the rank of 4 star General. On top of many military honors, she fought for sexual assault prevention in the United States Army.',
   'American Harriet Tubman was an abolisionist, humanitarian, and a spy during the American Civil War. Born a slave, she escaped and helped others to escape through her involvement with the Undeground Railroad. After the war, she advocated for women\'s right to vote. In 2016, the former U.S. Secretary of the Treasury proposed to put Harriet on the front of the 20 dollar bill, however, this was blocked by politician Steve Mnuchin.',
   'Dorothy Hodgkin was British chemist who was awarded the Nobel Prize for her work in protein crystallography, a technique that enabled her to map structure structure of penicillin,vitamin B12, and make contributions that were esential to later understanding the insulin molecule. She was the first British woman to win the Nobel Prize in Chemistry for her work, and the first woman to receive the Copley Medal, among many other awards.',
   'American Rosa Parks was a pivotal figure in the Civil Rights Movement. Famous for her refusal to give up her seat to a white passenger when the U.S. was still practicing racial segregation in 1955, she became an international symbol. Her arrest sparked a bus boycott that lasted over a year until the city of Montgomery finally repealed its law requiring segregation on public buses. Rosa was recognized by the U.S. Congress as the first lady of civil rights, she was awarded the Presidental Medal of Freedom, the Congressional Gold Medal, the Spingarn Medal, among others, and she is commenorated a statue in the National Statuary Hall.',
   'Argentinan Eva Peron, or Evita, as she was known, was a former First Lady of Argentina, remembered for her fight to end poverty and empower women. When she was turned away from the charity group traditionally led by the First Lady due to her impoverished upbringing and career as an actress, she started her own foundation, seeding it with her own money. Her foundation went on to employ thousands of workers, and built entire communities that still exist today.',
   'Samantha Bee is a Canadian-American comedian, feminist, writer and political commentator. She is best known for making our sides ache with laughter from her performances on The Daily Show and, since 2015, her show titled Full Frontal with Samantha Bee. She has won numerous awards in television and media, she raised over a million dollars with her natsy woman tee shirts for planned parenthood, and she even authored a vegan cookbook.',
   'Rachel Atherton is a British professional racing cyclist. She specializes in downhill mountain biking. Being hit head on by a truck in 2009 didn\'t stop her from returning to the sport. Rachel holds the world record for being the first woman to consecutively win 10 rounds of the World Cup, and for winning every round of a World Cup in the 2016 season.',
   'Emma Watson is an award winning British actress, feminist and model. She is best known for her breakout role as Hermione Granger in the Harry Potter film series. She speaks two languages, went to the Dragon School and later Brown University, she was the youngest person to appear on the cover of Teen Vogue, she is a UN Women Goodwill Ambassador, and she has a feminist book club called Goodreads.',
   'American Rachael Carson was a writer and marine biologist whose book titled Silent Spring is credited with starting the global environmental movement. Her skill in explaining scientific concepts in poetic, tangible ways, helped to warn a generation of the dangers of a pesticide called DDT. In Silent Spring, she exaplains how DDT accumulates in the fatty tissue of animals, which later goes up the food chain and ends up accumulating in human\'s fatty tissues, ultimately leading to genetic mutations and cancer. She was awarded the Presidential Medal of Freedom, included in a series of Great American postage stamps, she has research institutes, research vessels, parks, prizes and scholarships named after her, and even a Google Doodle.',
   'American Juliette Low founded the Girl Scouts in 1913. The Girl Scouts played a role in recovery following World War 1, assisting the Red Cross in making surgical dressings, knitting clothes for soliders, and growing and canning food. Today the World Assocation of Girl Guides and Girl Scouts has 146-member organizations and continues to work ot inspire girls and young women to reach their full potential as responsible citizens of the world.',
   'American Oprah Winfrey is a media icon, philantrhopist, actress and producer. Overcoming the disadvantages of poverty and childhood abuse, Time magazine and CNN have hailed her as the world\'s most powerful women. Above and beyond inventing her own style of talk show centered on self-improvement and spirituality, for 6 years she ranked among the 50 most generous Americans, she has donated hundreds of millions of dollars to educational causes and to non-profit organizations through her charity Oprah\'s Angel Network. She has won numerous awards and honors, including the Presidental Medal of Freedom.',
   'Ellen Degeneres is an American comedian, actress, writer, producer, TV host and LGBT activist. Best known for her role in the show Ellen, she was the first openly lesbian actress to play a lesbian character on TV. She later started her own talk show called The Ellen Degeneres show, where she is known for dancing and singing with her audience, and her generosity. She is a Special envoy for Global AIDS awareness, a vegan and animal rights activist, and she has won numerous awards and honors, including the Presidental Medal of Freedom. ',
   'Eva Longoria is an award winning American actress, producer, director, activist and philanthropist. She became popular in TV roles for the Young and The Restless and Desparate Housewives, among others. Eva has started two charitable organizations. Eva\'s Heroes helps developmentally disabled children and the Eva Longoria Foundation aims to close the education gap in the Latina community.',
   'Sally Ride was an American physicist and astronaut. She was the first American woman to travel to space, and the youngest astronaut to do so. She received numerous awards for her work, such as the NASA space flight medal, the von Braun Award, the Lindbergh Eagle, and she\'s a member of the Women\'s Hall of Fame and the Astronaut Hall of Fame.',
   'Lise Meitner was an Austrian-Swedish physicist. She was the first woman to become a full professor of Physics in Germany, a position she lost during the Nazi rule because of her Jewish background. She worked closely with colleague Otto Hahn and together they discovered new isotopes, including the first long-lived isotope discovered, protactinium. Han was  later awarded the Nobel Prize for the discovery of nuclear fission, but Lise was excluded. She has received numerous awards and honors for her work, and the element meitnerium is named in her honor.',
   'Emmy Noether was a German mathematician best known for her contributions in abstract algebra and theoretical physics. She spoke 2 langagues, was one of two female students at the university she attended, worked as a university lecturer without pay for nearly a decade because of her gender, and went on to make major contributions to the scientific community, such as developing the theories of rings, fields, and aglebras in mathematics, and Noether\'s theorem in physics, which discusses the connection between symmetry and conservation laws.',
   'Rosalyn Yalow was an American medical physist. She is best known for her work in developing the radioimmunoassay technique, or RIA, for which she and her collaborators received a Nobel Prize. The RIA technique allows for the detection of minute quantities of biological substances in the blood, and it has many applications, such as blood-screening or identifying specific health problems. She recevied numerous awards for her work, such as a Fulbright fellowship, AMA Scientific Achievement Award, and the National Medal of Science.',
   'American Gertrude Elion was a biochemist and pharmacologist best known for her work developing drugs called purines. She invented drugs utilized for the treatment of lukemia, bacterial infections, malaria, and as immunosuppressents, among others. She received many awards and honors for her work, including a Nobel Prize in Physiology or Medicine, she was a fellow of numerous scientific institutions, and she was the first woman to be inducted into the National Inventors Hall of Fame.',
   'Shirin Ebadi is an Iranian human rights lawyer, former judge, and a human rights activist. She founded of the Defenders of Human Rights Center in Iran and best known for work promoting democracy, and defending women and children. She was the Iranian and the first Muslim woman to receive the Nobel Peace Prize.',
   'Joanne Rowling, or as she is better known by her pen name J.K. Rowling, is a British author and producer best known for the Harry Potter book and film series. A feminist and social activist, she established the Volant Charitable Trust to address poverty and social injustice, and she lost her billionare status by donating funds to combat multiple sclerosis, to support child welfare and other educational initiatives. She has received numerous literary awards and film awards for her work.',
   'American Sandra Day O\'Connor is a retired Supreme Court justice. She was the first woman to sever as the female majority leader of a state senate, and she was the first woman to serve on the Supreme Court. She received numerous awards for leadership and service, such as the Elizabeth Blackwell Award, the Liberty Medal, the Presidential Medal of Freedom, and she\'s even been inducted into the Cowgirl Hal of Fame.',
   'American Jennifer Doudna is a biochemist and professor of chemisty best known for her contributions to genetic engineering, especially CRISPR genome editing. She and colleagues discovered that CRISPR, a family of DNA sequences found in bacteria, has a protein called Cas9 that acts like a pair of scissors to slice the DNA of viruses. They utilized this discovery to make a more efficient way for scientists to edit genomic DNA. Jennifer is the recipient of numerous scientific awards, such as the Alan T. Waterman Award, the Beckman Young Investigator\'s Award, and together with Emmanuelle Charpentier, she received the Breakthrough Prize in Life Sciences and the Japan Prize for her work on CRISPR/Cas9 genome editing technology.',
   'Emmanuelle Charpentier is a French researcher and professor best known for her work in developing CRISPR/Cas9 genome editing technology. Her work undercovered the molecular mechanisms in the CRISPR/Cas9 bacteria immune system, and together with Jennifer Doudna, she received the Breakthrough Prize in Life Sciences for this work. This method for genomic editing is being used by scientists around the world to edit DNA sequences. She has received numerous scientific awards for her work, such as the Gruber Foundation International Prize in Genetics, the Leibniz Prize, and the Japan Prize, among others.',
   'American Misty Copeland is a principal dancer with the American Ballet Theater, and she was the first black woman to hold this role at this company, and the first black female dancer at a major international ballet company. She has won numerous awards, such as the Leonore Annenberg Fellowship in the Arts, the National Youth of the Year Ambassador by the Boys and Girls Club, one of ESPN\'s impact 25 athletes and influencers, and one of Barabar Walter\'s top 10 most fascinating people, among others. Misty also has a barbie made in her likeness.',
   'Annelies or Ann Frank was a Jewish German citizen best known for her diary, which is one of the most widely read books in the world. Published after her death, The Diary of a Young Girl, candidly recounts her life during the German occupation of the Netherlands during World War 2. Her diary has inspired many books and films, and she was named one of the most important people of the century by Time magazine, as her words vividly paint a picture of the costs of war. ',
   'Angela Merkel is a German politician and the first female Chancellor of Germany. After receiving her Ph.D. in quantum chemistry, she was a researcher in her early career. She was elected to the German parliament in 1990 and has continuously been re-elected since then. She is best known for her efforts to stengthen European cooperation and trade agreements. She is often referred to as the de facto leader of the European Union. ',
   'Wangari Maathai was a Kenyan environmental activist, professor and stateswoman. She is best known for founding the Green Belt Movement. She was the first woman in Nairobi to be appointed as Senior Lecturer, department chair, and then Associate Professor, and the first African woman, and the first environmentalist, to receive the Nobel Peace Prize. She was an elected member of the Parliament, an assistant minister for environment and natural resources, and an honorary councillor of the World Future Council.',
   'Elizabeth Blackwell was a Bristish physician who made many firsts for women in the medical profession. She was the first woman to recieve a medical degree in the United States, and the first to be on the medical register in the United Kingdom. She worked to disrupt the social barriers keeping women out of medical school, helping to start a medical college for women before retiring.',
   'Marie Curie was a Polish-French scientist who accomplished many firsts for women. She was the first woman to win a Nobel Prize, the first person to win the Nobel Prize twice, and in two different categories, and the first woman to reach the rank of Professor at the University of Paris. She developed the theory of radioactivity, discovered 2 isotopes, started the Curie Research Insitutes in Paris, and developed mobile X-ray units.',
   'Barbara McClintock was an American cytogeneticist best known for her work with maize. She develeoped the technique for visualizing maize chromosomes using a microscope and produced the first genetic map for maize. She won many awards for her work and she was the first woman to win the Nobel Prize in Physiology and Medicine solo, and the first to win the National Medal of Science. ',
   'Maria Mayer was a German-American physicist best known for proposing the nuclear shell model of the atomic nucleus. She was awarded the Nobel Prize in Physics for her work and the Maria Goeppert Mayer Award was created by the American Physical Society to honor her legacy and provide support to early career female physists.',
   'Rosalind Franklin was an English chemist best known for her contributions to undertanding the molecular strucures of DNA and RNA. Her contributions in X-ray crystallography of DNA laid the foundation for the discovery of the DNA double helix. She also contributed to understanding the chemistry of coal and viruses. She was given many awards after her death and her exclusion from the Nobel Prize remains controversial today.',
   'Margaret Bourke-White was an American photographer who made many firsts for women. She is best recognized for her work in Russia. She was the first American female to become a war photojournalist, and the first to be permitted into combat zones during World War 2. She got her start taking photographs at a steele company and she later became the first female photojournalist hired by Life Magazine. She received many awards for her work, which is housed in museums throughout the US.',
   'Katharine Graham was an American publisher best known for being the first female publisher of a major American Newspaper, The Washington Post, and the first female to make the Fourtne 500 CEO list. Kay led the Washington Post during the Watergate scandal. She supported what was at the time very controverisal reporting, which was central to uncovering the scandal. She has won numerous awards for her work, including a Pulitzer for her memoir titled Personal History, and the Freedom Medal, among others.',
   'Barbara Walters is an American media icon and pioneer for women in broadcasting. She was the first woman to co-anchor an evening news show in the mid-1970s. She is best known for her contributions to NBC News, the Today Show, ABC Evening News and 20 20, and for developing and co-hosting The View, a daytime talk show led by all female hosts. She has received numerous awards for her work, including a Life Time Achievement Award from the National Academy of Television Arts and Sciences.',
   'Dolores Huerta in an American civil rights activist best known for contributions to women\'s and farm laborers rights. She co-founded the  Stockton Chapter of the Community Service Organization, which fought for economic improvements for Latinos, and she later co-founded the National Farmworkers Association, which helped farm workers to negotiate with agricultural employers. She also helped to organize the Delano Grape Strike in the mid-1960s, educating consumers about the treatement of farm laborers. She has won numerous awards for her work, such as the Eleanor Roosevelt Award for Human Rights, the Puffin Nation prizese for Creative Citizens, and she was the first Latina inducted into the National Women\'s Hall of Fame.',
   'Ella Baker was an American human rights activist best known for her contributions to the Civil Rights movement. She made substantial contributions to organizations such as the National Association for the Advancement of Colored People, the Southern Christian Leadership Conference, and the Student Nonviolent Coordinating Committee. She received numerous honors for her work, such as the Candace Award, films and documentaries have been written about her life, the University of California established the Ella Baker visiting professorship in her honor, and the Ella Baker Center for Human Rights in California was named after her.',
   'Florence Griffith-Joyner was an American track and field athlete best known for setting the world record for the 100 and 200 meter sprint. She won a silver medal and three gold medals in the Olympics and still holds the world record for fastest time in the 100 and 200 meter sprint. She was inducted into the USA Track and Field Hall of Fame, and numerous public parks and buildings are named in her honor.',
   'Hazel Scott was a Trinidadian performer best known for her abilities as a jazz singer and pianist. She was the first black woman to have her own TV show, titled the Hazel Scott Show, which aired in the 1950s. Hazel was one of the first black women to be cast in leading roles in film, refusing to take roles that stereotyped women and blacks. She is internationally renowned as one of the premier jazz performers of her time.',
   'Jovita Idar was an American journalist and civil rights activist best known for her work in advancing the civil rights of Mexican Americans. An educator and author, she worked to bring to light the harsh living conditions of Mexican-Amercian workers. She served as the first president of the League of Mexican Women, an organization providing free education to Mexican children, and traveled to Mexico to care for wounded individuals during the Mexican Revolution before returning to the US, where the founded the weekly papers Evolution and later, The Christian Herald.',
   'Maya Lin is an Amercian artist best known for her sculptures. She designed the Vietnam War Memorial in Washington D.C., which is a black, granite, V-shaped wall with the names of over 55000 fallen soliders engraved on it. It is meant to represent a wound in the Earth, conveying the gravity of lives lost. Subject to harassment because of her young age, gender, Asian-American background, Maya had to defend her design of the Memorial to the US Congress. Today the memorial is regarded as one of the more scared sites in America and is heavily visited. She has received numerous awards an honors for her work, such as the Rome Prize, the National Medal of Arts, and the Presidental Medal of Freedom, among others. ',
   'Zora Hurston was an American writer, anthropologist and ethnographer best known for her portrayal of the African-American experience and women\'s struggeles in particular in her novel titled Their Eyes Were Watching God. She was an active contributor during Harlem Renaissance, however, her work was largely unrecognized until after her death. Her Florida hometown celebrates a yearly fesitival and has erected a muesum in her honor, her house was dedicated a National Monument, and she has been inducted into the New York Writers Hall of Fame, the Alabama Writers Hall of Fame, and celebrated with a Google Doodle honoring her birthday.',
   'Virginia Apgar was an American obstetrical anesthesiologist best known for her contributions to the neonatology, or the medical care of newborn infants. She invented the Apgar score, a method for rapid assessment of a newborn infant\'s health administered in the first 5 minutes after birth. She was a strong advocate for maternal vaccinations during the rubella pandemic in the mid-1960s, she authored more than 60 scientific articles, essays, and a book. She received many awards and honors for her work, such as the Distinguised Service Award, Elizabeth Blackwell Award, and Alumni Gold Medal for Distinguised Achievement.',
   'Sonoia Sotomayor is an American lawyer and judge best known as the first American Supreme Court Justice of Hispanic descent and as the first Latina woman to hold this position. One of her most popular rulings ended the 1994-1995 baseball strike, which had lasted over 200 days, making her a bit hit with baseball fans. She has lectured at several univisities and received numerous awards and honors for her work, including numerous honorary law degrees, the Kathern Hepburn Medal, Columbia University\'s Outstanding Latino Professional Award, and Esquire Magazine\'s 75 most influential people of the twentyfirst century list.',
   'Elizabeh Seaman, known by her pen name of Nellie Bly, was an American journalist best recognized for her trip around the world. As an investigative journalist, she shed light on the working conditions for women in factories, committed herself to an insane asylum for an undercover assignment to expose the mistreatment of women, and traveled the world in approximately 72 days, which was a record at the time. She inspired musicals, books, and films. She was commemorated on a postage stamp, and inducted into the Women\'s Hall of Fame.',
   'Amy Sherald is an American painter and she best known for her portrait paintings. She was the first black female artist to paint a portrait for the presidental portraits at the Smithsonian National Portrait Gallery. She contributed a portrait of former First Lady Michelle Obama. Amy has won numerous awars and honors for her work, such as the Bethesa Painting Award, the Outwin Boochever Portrait Competition, she\'s had numerous solo and group exhibitions across the USA, and her work is showcased in servaral public collections.',
   'Vera Atkins was a Romanian-born British intelligence officer best known for her work during World War 2. She served as a flight officer in the Women\'s Auxillary Airforce and oversaw recruitment deployment for the Special Operations Executive in the French Section. Following World War 2, she worked for the United Nations Heritage Organization. She was awarded French military decorations and made knight in teh Legion of Honor by the French government.',
   'Melinda Gates is an American computer scientist and philanthropist best known for her philanthropy work with the Bill and Melinda Gates Foundation, which she co-founded. After working for Microsoft for a decade, she turned her focus to philanthropy. She has received numerous awards for her efforts to eliminate poverty and improve the healthcare globally, such as the Presidential Medal of Freedom and the Otto Hahn Peace Medal. Melinda is a strong advocate for gender equality and working to end the gender gap in technology.',
   'Nadia Comaneci was a Romanian gymnast best known for her Olympic performances, and being the first gymnast to be awarded a perfect score of 6.',
   'Venus Williams is an American tennis player and former number one tennis player in the world. She has won 7 Grand Slam single titles and 13 double titles. ',
   'Serena Williams is an American tennis player with 19 single Grand Slam titles, 15 doubles titles, and 4 Olympic Gold medals. ',
   'Marianne Vos is a Duth professional cyclist known for being one of the most successful female cyclists in the world. She holds world titles in cyclo-cross and road race and Olympic gold medals on the track.',
   'Chimamanda Adichie is a Nigerian writer and feminist best known for her works on gender and culture, her experiences as a black feminist, and motivating young people to discuss feminism. Her poems, short stories, and novels, have earned her international recognition. She\'s won numerous honors and awards for her work, such as the MacArthur Genius Grant, the O. Henry Award, and she was elected to the American Academy of Arts and Sciences.',
   'Anita Borg was an American computer scientist best known for her efforts to promote women in technology careers. She founded Systers, the Institute for Women and Technology, the Grace Hopper Celebration of Women in Computing, and the Institute for Women and Technology. She received her Ph.D. in computer science, where she focused her research on the synchronization efficiency of operating systems. She has received numerous awards for her research and advocacy work, such as the Augusta Ada Lovelace Award, the Heinz Award, and she served on the Presidential Commission on the Advancement of Women and Minorities in Science, Engineering, and Technology.',
   'Gisele Ben-Dor, born in Uruguy, is an American Israeli orchestra conductor best known for her work with Latin American music. Together with Georgina Ginastera, she created the Tango and Malambo Festival celebrating tango and malambo music. She later created the Revueltas festival, which celebrates the work of Mexican composer Silvestre Revueltas. She has held numerous posts as conductor or director, for example, with the Santa Barbara Symphony Orchestra, Houston Symphony Orcestra, Lousville Orchestra, and many others, and she is widely recognized as the world\'s finest conductor in the Latin American Music repertoire. ',
   'Estee Lauder was an American businesswoman best known for co-founding the cosmetics company Estee Lauder with her husband. She got her start working in the family hardware store and later for her uncle, who was a chemist with a business that sold cosmetics. She soon began developing and marketing her own products, which were a huge success. Estee received the Presidental Medal of Freedom, was inducted into the Business Hall of Fame, among other awards.',
   'Stephanie Kwolek was an American chemist best known for her invention of kevlar. She worked as a scientist at DuPont, where she was the first female to win the Lavoisier Medal for her work. She won numerous awards and honors for her work, such as the Perkin Medal, National Medal of Technology, and she was inducted into the National Inventor\'s Hall of Fame and the National Women\'s Hall of Fame. ',
   'Heddy Lamar, born in Austria, was an American actress and inventor best known for developing a radio guidance system for torpedos together with pianist George Antheil. Heddy was also a Hollywood actress who starred in numerous films.' ,
   'Eleanor Roosevelt as an American politician, activist, and former First Lady best known for her work as as human rights activist. She was the longest serving First Lady, as her husband served 4 terms in office. She was highly engaged in politics throughout this time, regularly holding press coferences, publishing newspapers, and attending political events. While serving as the head of the United Nation\'s Human Rights commission, she helped draft the 1948 United Nation\'s Declaration of Human Rights. ',
   'Annie Besant ',
   'Betty Williams Ireland',
   'Tegla Loroupe  Kenya',
   'Larisa Latynina ',
   ''
];

//=========================================================================================================================================
//Editing anything below this line might break your skill.
//=========================================================================================================================================

exports.handler = function(event, context, callback) {
    var alexa = Alexa.handler(event, context);
    alexa.appId = APP_ID;
    alexa.registerHandlers(handlers);
    alexa.execute();
};

const handlers = {
    'LaunchRequest': function () {
        this.emit('GetNewFactIntent');
    },
    'GetNewFactIntent': function () {
        const factArr = data;
        const factIndex = Math.floor(Math.random() * factArr.length);
        const randomFact = factArr[factIndex];
        const speechOutput = GET_FACT_MESSAGE + randomFact;

        this.response.cardRenderer(SKILL_NAME, randomFact);
        this.response.speak(speechOutput);
        this.emit(':responseReady');
    },
    'AMAZON.HelpIntent': function () {
        const speechOutput = HELP_MESSAGE;
        const reprompt = HELP_REPROMPT;

        this.response.speak(speechOutput).listen(reprompt);
        this.emit(':responseReady');
    },
    'AMAZON.CancelIntent': function () {
        this.response.speak(STOP_MESSAGE);
        this.emit(':responseReady');
    },
    'AMAZON.StopIntent': function () {
        this.response.speak(STOP_MESSAGE);
        this.emit(':responseReady');
    },
};
